-- MySQL Script generated by MySQL Workbench

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema expoCalendar
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `expoCalendar` ;

-- -----------------------------------------------------
-- Schema expoCalendar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `expoCalendar` DEFAULT CHARACTER SET utf8 ;
USE `expoCalendar` ;

-- -----------------------------------------------------
-- Table `expoCalendar`.`exhibition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expoCalendar`.`exhibition` (
  `exhibitionId` INT NOT NULL AUTO_INCREMENT,
  `exhibitionName` VARCHAR(255) NOT NULL,
  `price` INT NOT NULL,
  `exhibStart` DATE NOT NULL,
  `exhibEnd` DATE NOT NULL,
  PRIMARY KEY (`exhibitionId`));


-- -----------------------------------------------------
-- Table `expoCalendar`.`expoHall`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expoCalendar`.`expoHall` (
  `expoHallId` INT NOT NULL AUTO_INCREMENT,
  `expoHallName` VARCHAR(100) NOT NULL,
  `expo_exhibitionId` INT NOT NULL,
  PRIMARY KEY (`expoHallId`),
  INDEX `fk_expoHall_Exhibitions1_idx` (`expo_exhibitionId` ASC),
  CONSTRAINT `fk_expoHall_Exhibitions1`
    FOREIGN KEY (`expo_exhibitionId`)
    REFERENCES `expoCalendar`.`Exhibitions` (`exhibitionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `expoCalendar`.`visitor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expoCalendar`.`Visitor` (
  `visitorId` INT NOT NULL AUTO_INCREMENT,
  `visitorName` VARCHAR(100) NOT NULL,
  `login` VARCHAR(50) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `isAdmin` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`visitorId`));


-- -----------------------------------------------------
-- Table `expoCalendar`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expoCalendar`.`payment` (
  `paymentId` INT NOT NULL AUTO_INCREMENT,
  `paymentTime` TIMESTAMP(1) NOT NULL DEFAULT NOW(),
  `patmentVisitorId` INT NOT NULL,
  `total` INT NOT NULL,
  PRIMARY KEY (`paymentId`),
  INDEX `fk_Payment_Visitors1_idx` (`patmentVisitorId` ASC),
  CONSTRAINT `fk_Payment_Visitors1`
    FOREIGN KEY (`patmentVisitorId`)
    REFERENCES `expoCalendar`.`Visitors` (`visitorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table `expoCalendar`.`ticket`
-- -----------------------------------------------------
CREATE TABLE `ticket` (
  `ticketId` int(11) NOT NULL AUTO_INCREMENT,
  `ticketIsSold` tinyint(1) NOT NULL DEFAULT '0',
  `ticket_exhibitionId` int(11) NOT NULL,
  `ticket_paymentId` int(11) NOT NULL,
  PRIMARY KEY (`ticketId`),
  KEY `fk_ticket_exhibitionId_idx` (`ticket_exhibitionId`),
  CONSTRAINT `fk_ticket_exhibitionId` FOREIGN KEY (`ticket_exhibitionId`) REFERENCES `exhibition` (`exhibitionid`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
